# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish to pypi
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - run: python -m pip install --upgrade pip
      - run: pip install setuptools wheel twine build
